### ISSUE TITLE
Error on start (Paper 1.16.1, using EssentialsX-2.18.0.0, Vault-1.7.3-b131, HyperConomyX-0.10.0)

### ISSUE THREAD

**Issue by Orendigo** [RedTech64/HyperConomyX#4]
Error Log:
`[18:53:46 INFO]: 0
[18:53:46 INFO]: hyperconomy
[18:53:46 WARN]: [HyperConomy] Task #15 for HyperConomy v0.10.0 generated an exception
java.lang.NullPointerException: null
        at net.milkbowl.vault.economy.AbstractEconomy.hasAccount(AbstractEconomy.java:10) ~[?:?]
        at regalowl.hyperconomy.bukkit.BukkitEconomy.hasAccount(BukkitEconomy.java:29) ~[?:?]
        at regalowl.hyperconomy.account.HyperPlayer.checkExternalAccount(HyperPlayer.java:107) ~[?:?]
        at regalowl.hyperconomy.account.HyperPlayer.validate(HyperPlayer.java:101) ~[?:?]
        at regalowl.hyperconomy.account.HyperPlayer.<init>(HyperPlayer.java:75) ~[?:?]
        at regalowl.hyperconomy.account.HyperPlayerManager$2.run(HyperPlayerManager.java:52) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-128]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-128]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-128]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-128]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-128]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-128]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-128]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]`

Happens on every restart, commands do not work when in-game.  This happens regardless of changing values in the economy-plugin config section.

**Comment by Orendigo** [comment]
I should note the same error occurs on Version 0.10.1.

**Comment by coleweinman** [comment]
@Orendigo Can you confirm that "use-external" is set to false? Try installing Vault if it is.
